<?php
$store = $this->getStore();
$method = $store->getPaymentMethod('arsenalpay');
$methodId = $method->getId();
$methodInstance = $method->getInstance();
?>

<div class="form-group arsenalpay_data">
    <div class="col-sm-3">
        <label for="arsenalpay_widget_id"><?php echo __("Widget id:"); ?> <span>*</span></label>
    </div>
    <div class="col-sm-5">
        <input type="text"
               id="arsenalpay_widget_id"
               class="input-flat required"
               name="details_payment_methods[<?php echo $this->getMethodId(); ?>][widget_id]"
               value="<?php echo $methodInstance->getWidgetId(); ?>"
               placeholder="<?php echo __('Widget id:'); ?>" />
    </div>
</div>
<div class="form-group arsenalpay_data">
    <div class="col-sm-3">
        <label for="arsenalpay_widget_key"><?php echo __("Widget key:"); ?> <span>*</span></label>
    </div>
    <div class="col-sm-5">
        <input type="text"
               id="arsenalpay_widget_key"
               class="input-flat required"
               name="details_payment_methods[<?php echo $this->getMethodId(); ?>][widget_key]"
               value="<?php echo $methodInstance->getWidgetKey(); ?>"
               placeholder="<?php echo __('Widget key'); ?>" />
    </div>
</div>
<div class="form-group arsenalpay_data">
    <div class="col-sm-3">
        <label for="arsenalpay_secret">
            <?php echo __("Callback Key:"); ?> <span>*</span>
        </label>
    </div>
    <div class="col-sm-5">
        <input type="text"
               id="arsenalpay_secret"
               class="input-flat required"
               name="details_payment_methods[<?php echo $this->getMethodId(); ?>][secret]"
               value="<?php echo $methodInstance->getSecret(); ?>"
               placeholder="<?php echo __('Callback Key'); ?>" />
    </div>
</div>

<div class="form-group arsenalpay_data">
<div class="col-sm-3">
<label for="arsenalpay_callback_url"><?php echo $this->_("Callback URL:"); ?></label>
</div>
<div class="col-sm-5">
<div style="white-space: nowrap; overflow-x: scroll" id="arsenalpay_callback_url" class="input-flat"><?php echo "https://".$_SERVER['SERVER_NAME']."/arsenalpay/callback/payment"; ?></div>
</div>
</div>

